spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: sitidev
    password: Cloud@002
    url: jdbc:mysql://47.100.200.255:3306/recruit_release?useUnicode=true&characterEncoding=utf8&useSSL=true&allowMultiQueries=true&serverTimezone=UTC


filePath:
  invalidFileDelete: 0    # 无效文件立即删除
  images: C:/test/images/    # 文件服务器地址
  files: C:/test/files/    # 文件服务器地址


logback:
  logHome: c:/audit/log/
  logName: hiringplatform

redis:
  addr: redis://127.0.0.1:6379
  password: Cloud@002

msg:
  accountSid: 8a216da855826478015599e3f66e1411
  authToken: 71a6619327734d81957e60f2eeaa2626
  appId: 8a216da86c8a1a54016c8dc74f1c0182
  serberRip: app.cloopen.com
  serverPort: 8883
  msgModelId: 492507

