spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    username: sitidev
    password: Cloud@002
    url: jdbc:mysql://47.100.200.255:3306/recruit_release?useUnicode=true&characterEncoding=utf8&useSSL=true&allowMultiQueries=true


filePath:
  invalidFileDelete: 0    # 无效文件立即删除
  images: C:/test/images/    # 文件服务器地址
  files: C:/test/files/    # 文件服务器地址


logback:
  logHome: c:/audit/log/
  logName: hiringplatform

redis:
  addr: redis://127.0.0.1:6379
  password: Cloud@002