spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    password: root
    url: jdbc:mysql://localhost:3306/sarikindnessplat?useUnicode=true&characterEncoding=utf8&useSSL=true&allowMultiQueries=true

filePath:
  invalidFileDelete: 0    # 无效文件立即删除
  images: C:/test/images/    # 文件服务器地址
  files: C:/test/files/    # 文件服务器地址

#  uploadFiles: C:/bikeFile/uploadFile/ #导入文件存放地址

logback:
  logHome: c:/audit/log/
  logName: hiringplatform

msg:
  accountSid: 8a216da855826478015599e3f66e1411
  authToken: 71a6619327734d81957e60f2eeaa2626
  appId: 8a216da86c8a1a54016c8dc74f1c0182
  serberRip: app.cloopen.com
  serverPort: 8883
  msgModelId: 564132

